@component('mail::message')
Dear <strong>{{ $name }}</strong>

<br>
<strong>Subjek :</strong> {{ $subjects }}
<br>
<strong>Pesan :</strong> {{ $message }}
<br>
<br>

Disini boleh diisikan informasi tambahannya

@component('mail::button', ['url' => env('APP_URL')])
Kunjungi kami
@endcomponent

Thanks,<br><br

><i>
    This is autogenerated email please do not reply.
</i>
{{ config('app.name') }}
@endcomponent
